server:
  servlet:
    session:
      cookie:
        name: Sneakydog_distinctid

spring:
  application:
    name: sneakydog-spring-authorization-server-demo
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    hikari:
      max-lifetime: 31000
