server:
  servlet:
    session:
      cookie:
        name: Sneakydog_distinctid

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    hikari:
      max-lifetime: 31000


application:
  security:
    oauth2:
      issuerUrl: ${JWT_ISSUER_URI:http://localhost:8080}
    excludeUrls:
      - "/actuator/**"
      - "/upload/file"
  minio:
    enable: true
    endpoint: http://127.0.0.1:9000
    accessKeyId: minio
    accessKeySecret: 1234567890
    bucketName: "my.example.s3.bucket"
